<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>de.jotschi.ai</groupId>
	<artifactId>dataset-processor</artifactId>
	<version>0.0.1-SNAPSHOT</version>


	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<compiler-plugin.version>3.14.0</compiler-plugin.version>
	</properties>


	<dependencies>
		<!-- Dataset support -->
		<dependency>
			<groupId>org.apache.arrow</groupId>
			<artifactId>arrow-dataset</artifactId>
			<version>18.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.arrow</groupId>
			<artifactId>arrow-memory-netty</artifactId>
			<version>18.3.0</version>
			<scope>runtime</scope>
		</dependency>

		<dependency>
			<groupId>me.tongfei</groupId>
			<artifactId>progressbar</artifactId>
			<version>0.10.0</version>
		</dependency>

		<dependency>
			<groupId>io.metaloom.utils</groupId>
			<artifactId>genai-utils</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>io.metaloom.utils</groupId>
			<artifactId>hash-utils</artifactId>
			<version>0.5.0-SNAPSHOT</version>
		</dependency>

		<!--Test -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>5.14.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>3.25.1</version>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${compiler-plugin.version}</version>
				<configuration>
					<release>24</release>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>